source "https://rubygems.org/"

gem "sinatra", "~> 1.3.2"
gem "sinatra-websocket", "~> 0.1.2"
gem "data_mapper", "~> 1.2.0"
gem "dm-sqlite-adapter", "~> 1.2.0"
gem "thin", "~> 1.3.1"
gem "rest-client", "~> 1.6.7"
gem "rdiscount", "~> 1.6.8"
gem "erubis", "~> 2.7.0"
gem "eventmachine", "~> 0.12.10"
